spring:
    application:
        name: VirtualThreadCircuitBreakerExample

    threads:
        virtual:
            enabled: true




logging:
    level:
        org:
            springframework:
                scheduling: DEBUG

        com:
            example:
                virtualThreadCircuitBreakerExample: DEBUG